version: '3'

volumes:
  movirama_local_movies_postgres_data: {}
  movirama_local_movies_postgres_data_backups: {}
  movirama_local_elasticsearch_data: {}

services:
  elasticsearch:
    build:
      context: .
      dockerfile: ./compose/elasticsearch/Dockerfile
    image: movirama_local_elasticsearch
    container_name: movirama_local_elasticsearch
    depends_on:
      - movies_postgres
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    cap_add:
      - IPC_LOCK
    volumes:
      - movirama_local_elasticsearch_data:/usr/share/elasticsearch/data
  flask:
    build:
      context: .
      dockerfile: ./compose/flask/Dockerfile
    image: movirama-local_flask
    container_name: movirama_local_flask
    depends_on:
      - elasticsearch
      - movies_postgres
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.flask
    ports:
      - "8080:8000"
      - "2992:2992"
    command: /start
  movies_postgres:
      build:
        context: .
        dockerfile: ./compose/movies_postgres/Dockerfile
      image: movirama_local_movies_postgres
      container_name: movirama_local_movies_postgres
      volumes:
        - movirama_local_movies_postgres_data:/var/lib/postgresql/data
        - movirama_local_movies_postgres_data_backups:/backups
      env_file:
        - ./.envs/.local/.movies_postgres
  # django:
  #   build:
  #     context: .
  #     dockerfile: ./compose/django/Dockerfile
  #   image: movirama_local_django
  #   container_name: movirama_local_django
  #   depends_on:
  #     - postgres
  #     - redis
  #   volumes:
  #     - .:/app:z
  #   env_file:
  #     - ./.envs/.local/.django
  #     - ./.envs/.local/.postgres
  #   ports:
  #     - '8000:8000'
  #   command: /start
